//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float3 CameraWorldPos;
//   float4 MinZ_MaxZRatio;
//   sampler2D PixelTexture2D_0;
//   sampler2D PixelTexture2D_1;
//   sampler2D PixelTexture2D_2;
//   float4 UniformPixelScalars_0;
//   float4 UniformPixelScalars_1;
//   float4 UniformPixelScalars_2;
//   float4 UniformPixelScalars_3;
//   float4 UniformPixelVector_0;
//   float4 UniformPixelVector_1;
//   float4 UniformPixelVector_2;
//   float4 UniformPixelVector_3;
//   float4 UniformPixelVector_4;
//   float4 UniformPixelVector_5;
//   float4 UniformPixelVector_6;
//   float4 UniformPixelVector_7;
//   float4 UniformPixelVector_8;
//   float4 UniformPixelVector_9;
//   float4x4 ViewProjectionMatrix;
//
//
// Registers:
//
//   Name                  Reg   Size
//   --------------------- ----- ----
//   CameraWorldPos        c0       1
//   MinZ_MaxZRatio        c2       1
//   ViewProjectionMatrix  c8       4
//   UniformPixelVector_0  c12      1
//   UniformPixelVector_1  c13      1
//   UniformPixelVector_2  c14      1
//   UniformPixelVector_3  c15      1
//   UniformPixelVector_4  c16      1
//   UniformPixelVector_5  c17      1
//   UniformPixelVector_6  c18      1
//   UniformPixelVector_7  c19      1
//   UniformPixelVector_8  c20      1
//   UniformPixelVector_9  c21      1
//   UniformPixelScalars_0 c22      1
//   UniformPixelScalars_1 c23      1
//   UniformPixelScalars_2 c24      1
//   UniformPixelScalars_3 c25      1
//   PixelTexture2D_0      s0       1
//   PixelTexture2D_1      s1       1
//   PixelTexture2D_2      s2       1
//

    ps_3_0
    def c1, 0.100000001, 3, 2, -10
    def c3, 0.075000003, -0.5, -0.25, -0.75
    def c4, 0.600000024, 0.298999995, 0.587000012, 0.114
    def c5, 9.99999997e-007, 2.20000005, 0, 0
    def c6, -9.99999975e-005, 10000, 1, 0
    def c7, 1, 0.5, -0.497000009, -0.5
    def c26, 2, 0, 4.01999998, 1
    dcl_color1 v0.xyz
    dcl_texcoord v1.xy
    dcl_texcoord6 v2.x
    dcl_texcoord5 v3
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    add r0.xyz, c0, v3
    mad r0.w, r0.y, c1.z, r0.z
    add r0.w, r0.w, c1.w
    max r1.x, -c1.z, r0.w
    min r0.w, r1.x, c6.w
    add r0.w, r0.w, c22.w
    add r1.xy, r0.w, c7
    mov_sat r1.x, r1.x
    cmp r0.w, r1.y, r1.x, c7.y
    mov r1.z, c6.z
    add r1.x, r1.z, -c16.w
    rcp r1.x, r1.x
    add r2.xyz, -r0, c16
    add r0.xyz, -r0, c0
    nrm r3.xyz, r0
    dp3 r0.x, r2, r2
    rsq r0.x, r0.x
    rcp r0.y, r0.x
    add r0.y, r0.y, c6.x
    cmp r0.y, r0.y, r0.x, c6.y
    mad r2.xyz, r2, r0.x, -c18
    mul_sat r0.x, r0.y, c15.w
    mad r0.y, r0.x, r0.x, -c16.w
    mul r4.xyz, r0.x, c15
    mov r1.y, c1.y
    mad r4.xyz, r4, r1.y, -c17
    mul r0.x, r1.x, r0.y
    max r1.x, r0.x, c6.w
    mad r0.xyz, r1.x, r2, c18
    nrm r2.xyz, r0
    nrm r0.xyz, v0
    dp3 r1.y, r2, r0
    add r2.xyz, r2, r2
    dp3 r1.w, r0, r3
    mul r2.w, r1.w, c23.x
    add r1.w, -r1.w, c6.z
    add r2.w, r1.y, r2_abs.w
    add r2.w, r2.w, c6.z
    mul r0.w, r0.w, r2.w
    texld r5, v1, s2
    mul r0.w, r0.w, r5.y
    mul r0.w, r0.w, v2.x
    mov r6.z, c7.z
    mad r0.w, c23.z, r0.w, r6.z
    mad r4.xyz, r1.x, r4, c17
    add r4.xyz, r4, r4
    mul r2.w, r1.x, c1.x
    mad r6.xyz, r1.x, -r2.w, c14
    texld r7, v1, s0
    mul r6.xyz, r6, r7
    add r6.xyz, r6, r6
    cmp r8.xyz, r0.w, r4, r6
    mul r4.xyz, r4, c19
    add r0.w, r1.y, c1.x
    add r0.w, r0_abs.w, c6.z
    mul r0.w, r1.w, r0.w
    mad r0.w, r0.w, c7.y, c7.w
    texld r9, v1, s1
    mul r1.x, r9.w, c23.w
    mul r1.x, r1.x, c3.x
    cmp r0.w, r0.w, r1.x, c6.w
    add r8.xyz, r0.w, r8
    add r10.xyz, r7, c7.y
    mul r7.xyz, r7, r9
    mul r6.xyz, r6, r10
    mad r6.xyz, r6, c4.x, -r8
    add r10.xyz, r5.xxyw, c3.zwyw
    cmp r0.w, r10.z, c26.x, c26.y
    mov_sat r10.xy, r10
    add r0.w, r0.w, r1.y
    mad r1.x, v2.x, -c26.z, c26.w
    add r0.w, r0.w, -r1.x
    cmp r0.w, r0.w, c6.w, c6.z
    add r1.x, r5.y, -c24.x
    cmp r0.w, r1.x, r0.w, c6.z
    mul_sat r0.w, r0.w, c24.y
    mad r6.xyz, r0.w, r6, r8
    mul r6.xyz, r9, r6
    mad r4.xyz, r5.x, r4, r6
    mul r0.w, r10.x, -c1.w
    mul r1.x, r10.y, c25.x
    mad r2.xyz, r0.w, r3, r2
    nrm r3.xyz, r2
    dp3 r0.x, r3, r0
    mul r0.y, r1.w, r1.w
    mul r0.y, r0.y, r0.y
    mul r0.y, r0.y, r1.w
    mul r0.y, r1.x, r0.y
    mul r0.z, v2.x, v2.x
    mul r0.z, r0.z, v2.x
    mad r0.x, r0.z, r0.y, r0_abs.x
    mul r0.x, r0.x, r0.x
    mul r0.x, r0.x, r0.x
    add r0.y, -r5.z, c6.z
    mul r0.z, c24.z, v2.x
    mad r0.x, r0.z, r0.x, -r0.y
    cmp r0.xyz, r0.x, r4, r6
    add r1.xyw, c14.xyzz, c14.xyzz
    mad r1.xyw, r1, r7.xyzz, -c13.xyzz
    mad r1.xyw, c13.w, r1, c13.xyzz
    lrp r2.xyz, r5.w, r0, r1.xyww
    dp3 r0.x, c4.yzww, r2
    lrp r1.xyw, c25.y, r2.xyzz, r0.x
    mov r0.xyz, c20
    mad r0.xyz, r1.xyww, r0, c21
    max r1.xyw, r0_abs.xyzz, c5.x
    log r0.x, r1.x
    log r0.y, r1.y
    log r0.z, r1.w
    mul r0.xyz, r0, c5.y
    exp_sat r2.x, r0.x
    exp_sat r2.y, r0.y
    exp_sat r2.z, r0.z
    add_pp oC0.xyz, r2, c12
    mul r0.x, c9.w, v3.y
    mad r0.x, c8.w, v3.x, r0.x
    mad r0.x, c10.w, v3.z, r0.x
    mad r0.x, c11.w, v3.w, r0.x
    rcp r0.x, r0.x
    add r0.y, r1.z, -c2.y
    mad oC0.w, -c2.x, r0.x, r0.y

// approximately 129 instruction slots used (3 texture, 126 arithmetic)

