/* This file was autogenerated. Do not edit! */
#ifndef _INCL_MOJOSHADER_VERSION_H_
#define _INCL_MOJOSHADER_VERSION_H_
#define MOJOSHADER_VERSION 1299
#define MOJOSHADER_CHANGESET "hg-1299:02d36217591b"
#endif

